"""add topic_order in Article

Revision ID: 70e98d52e507
Revises: bcc5262c9c32
Create Date: 2017-05-27 14:36:08.192475

"""

# revision identifiers, used by Alembic.
revision = '70e98d52e507'
down_revision = 'bcc5262c9c32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Article', sa.Column('topic_order', sa.Integer(), nullable=True))
    # op.create_index(op.f('ix_User_name'), 'User', ['name'], unique=True)
    # op.drop_index('ix_User_name', table_name='User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_User_name', 'User', ['name'], unique=True)
    # op.drop_index(op.f('ix_User_name'), table_name='User')
    op.drop_column('Article', 'topic_order')
    # ### end Alembic commands ###
