"""add Topicmodel and isDeleted column

Revision ID: a06c8b2e1c5e
Revises: 9915bfbfb858
Create Date: 2017-05-27 13:30:42.810888

"""

# revision identifiers, used by Alembic.
revision = 'a06c8b2e1c5e'
down_revision = '9915bfbfb858'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.add_column('Article', sa.Column('isDeleted', sa.Boolean(), nullable=True))
    op.add_column('Category', sa.Column('isDeleted', sa.Boolean(), nullable=True))
    # op.create_index(op.f('ix_User_name'), 'User', ['name'], unique=True)
    # op.drop_index('ix_User_name', table_name='User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_User_name', 'User', ['name'], unique=True)
    op.drop_index(op.f('ix_User_name'), table_name='User')
    op.drop_column('Category', 'isDeleted')
    op.drop_column('Article', 'isDeleted')
    op.drop_table('Topic')
    # ### end Alembic commands ###
