"""add topic_id foreignkey in Article

Revision ID: bcc5262c9c32
Revises: 0b6f90cadb82
Create Date: 2017-05-27 13:55:36.008805

"""

# revision identifiers, used by Alembic.
revision = 'bcc5262c9c32'
down_revision = '0b6f90cadb82'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Article', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Article', 'Topic', ['topic_id'], ['id'])
    # op.create_index(op.f('ix_User_name'), 'User', ['name'], unique=True)
    # op.drop_index('ix_User_name', table_name='User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_User_name', 'User', ['name'], unique=True)
    # op.drop_index(op.f('ix_User_name'), table_name='User')
    op.drop_constraint(None, 'Article', type_='foreignkey')
    op.drop_column('Article', 'topic_id')
    # ### end Alembic commands ###
